### ISSUE TITLE
http/https

### ISSUE THREAD

**Issue by ilchuk96** [ilchuk96/DiaryWhoCares#1]
Проблема в том, что сейчас на запросы нет ответа. Решение. Запросы отсылать СТРОГО на `https://diarywhocares.tk`. Пока так, да.

**Comment by ilchuk96** [comment]
И это норм, что в логах `nginx` все равно пишет `http`?

**Comment by ValchukDmitry** [comment]
> И это норм, что в логах nginx все равно пишет http?
AFAIK норм, но редирект с 80 на 443 все равно стоит сделать
